language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - coverage run --source='.' manage.py test
after_success:
  - codecov